export const CoursesList = [
  {
    "Sl No.": 41,
    Course: "Advanced Diploma Courses",
    Description: "Advanced Diploma Courses",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 188,
    Course: "Aircraft Maintenance Engieerin",
    Description: "Aircraft Maintenance Engieering",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 42,
    Course: "Allied health science",
    Description: "Allied health science",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 43,
    Course: "ANM",
    Description: "ANM",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 17,
    Course: "Ayurveda PG",
    Description: "AYURVEDA PG",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 189,
    Course: "B Arch",
    Description: "Bachelor of Architech",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 3,
    Course: "BA",
    Description: "Bachelor of Arts",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 52,
    Course: "BA LLB",
    Description: "Bachelor of Arts &amp; Law",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 19,
    Course: "BAMS",
    Description: "Bachelor of Ayurvedic Medical SciencesÂ",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 5,
    Course: "BBA",
    Description: "Bachelor of Busines Administration",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 53,
    Course: "BBA LLB",
    Description: "Bachelor of Busines Administration &amp; Law",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 6,
    Course: "BBS",
    Description: "Bachelor of Business Studies",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 1,
    Course: "B Com",
    Description: "Bachelor of commerce",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 44,
    Course: "B Com LLB",
    Description: "Bachelor of Commerce &amp; Law",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 55,
    Course: "BCJ",
    Description: "Bachelor of Communication &amp; Journalism",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 7,
    Course: "BCA",
    Description: "Bachelor of Computer Application",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 20,
    Course: "BDS",
    Description: "Bachelor of dental surgeryÂ",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 45,
    Course: "B Desgn",
    Description: "Bachelor of Designs",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 46,
    Course: "B Ed",
    Description: "Bachelor of Education",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 191,
    Course: "BE",
    Description: "Bachelor of Engineering",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 192,
    Course: "BFT",
    Description: "Bachelor of Fashion Technology",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 8,
    Course: "BFA",
    Description: "Bachelor of Fine Arts",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 9,
    Course: "BFSc",
    Description: "Bachelor of Fisheries Science",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 21,
    Course: "BHMS",
    Description: "Bachelor of Homeopathy Medicine &amp; SurgeryÂ",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 57,
    Course: "BHM",
    Description: "Bachelor of Hotel management",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 22,
    Course: "BLT",
    Description: "Bachelor of Lab Technology",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 145,
    Course: "LLB",
    Description: "Bachelor of Law",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 58,
    Course: "BLS",
    Description: "Bachelor of Library Sciencce",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 31,
    Course: "MBBS",
    Description: "Bachelor of Medicine and Bachelor of Surgery",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 4,
    Course: "BACHELOR OF MUSIC",
    Description: "BACHELOR OF MUSIC",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 23,
    Course: "BNYS",
    Description: "Bachelor of Naturopathy and Yogic Science",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 59,
    Course: "BNg",
    Description: "Bachelor of Nursing",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 60,
    Course: "BPA",
    Description: "Bachelor of Performance Arts",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 48,
    Course: "B Pharma",
    Description: "Bachelor of Pharmacy",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 47,
    Course: "B PEd",
    Description: "Bachelor of Physical Education",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 18,
    Course: "Bachelor of Physio Therapy",
    Description: "Bachelor of Physio Therapy",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 24,
    Course: "BPT",
    Description: "Bachelor of Physioptherapy",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 49,
    Course: "B Plan",
    Description: "Bachelor of Planning",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 2,
    Course: "B Sc",
    Description: "Bachelor of Science",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 50,
    Course: "B Sc (Nursing)",
    Description: "Bachelor of Science (Nursing)",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 10,
    Course: "BSW",
    Description: "Bachelor of Social Work",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 190,
    Course: "B Tech",
    Description: "Bachelor of Technology",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 64,
    Course: "BTH",
    Description: "Bachelor of Tourism &amp; Hospitality",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 63,
    Course: "BTA",
    Description: "Bachelor of Tourism Administration",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 65,
    Course: "BTTM",
    Description: "Bachelor of Travel &amp; Tourism Management",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 25,
    Course: "BUMS",
    Description: "Bachelor of Unani Medicine &amp; Surgery",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 68,
    Course: "BVSC",
    Description: "Bachelor of Veterinary Science",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 69,
    Course: "BVSc and AH",
    Description: "Bachelor of Veterinary Science &amp; Animal Husband",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 66,
    Course: "BVA",
    Description: "Bachelor of Visual Arts",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 51,
    Course: "B Voc",
    Description: "Bachelor of Vocational",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 56,
    Course: "BHA",
    Description: "Bachelors in Hospital Administration",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 61,
    Course: "BPH",
    Description: "Bachelors in public Health",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 54,
    Course: "BBT",
    Description: "BBT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 88,
    Course: "D Ed",
    Description: "Diplamo in Education",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 89,
    Course: "D Pharma",
    Description: "Diplamo in Pharmacy",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 112,
    Course: "Diploma Courses",
    Description: "Diploma Courses",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 26,
    Course: "DA",
    Description: "Diploma in Anaesthetics",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 27,
    Course: "DFM (FORENSIC)",
    Description: "Diploma in Forensic Medicine",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 29,
    Course: "DOMS (OPTHOLMOLOGY)",
    Description: "Diploma inÂ OphthalmicÂ Medicine and Surgery",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 28,
    Course: "DM",
    Description: "Doctor of Medicine",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 11,
    Course: "INTEGRATED B Sc",
    Description: "INTEGRATED B Sc",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 12,
    Course: "INTEGRATED BA",
    Description: "INTEGRATED BA",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 143,
    Course: "Integrated MBA",
    Description: "Integrated MBA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 144,
    Course: "ITI Courses",
    Description: "ITI Courses",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 152,
    Course: "M Sc (NURSING)",
    Description: "M Sc (NURSING)",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 153,
    Course: "Master in Marketing",
    Description: "Master in Marketing",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 194,
    Course: "M Arch",
    Description: "Master of Architechture",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 15,
    Course: "MA",
    Description: "Master of Arts",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 155,
    Course: "MBA",
    Description: "Master of Business Administration",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 156,
    Course: "MBE",
    Description: "Master of Business Economics",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 157,
    Course: "MBS",
    Description: "Master of Business Studies",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 13,
    Course: "M Com",
    Description: "Master of Commerce",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 159,
    Course: "MCJ",
    Description: "Master of Communication Journalism",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 158,
    Course: "MCA",
    Description: "Master of Computer Application",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 33,
    Course: "MDS",
    Description: "Master of Dental Surgery",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 147,
    Course: "M Desgn",
    Description: "Master of Design",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 148,
    Course: "M Ed",
    Description: "Master of Education",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 196,
    Course: "ME",
    Description: "Master of Engineering",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 161,
    Course: "MFM",
    Description: "Master of Fashion Management",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 197,
    Course: "MFT",
    Description: "Master of Fashion Technology",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 160,
    Course: "MFA",
    Description: "Master of Finance and AccountingÂ",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 34,
    Course: "MHA(HEALTH)",
    Description: "Master of Health Administration",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 163,
    Course: "MHM",
    Description: "Master of Hospital Management",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 162,
    Course: "MHM",
    Description: "Master of Hotel Management",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 154,
    Course: "Master of International Busines",
    Description: "Master of International Business",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 167,
    Course: "MMS",
    Description: "Master of Management Studies",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 168,
    Course: "MPA",
    Description: "Master of Performing Arts",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 150,
    Course: "M Pharma",
    Description: "Master of Pharmacy",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 151,
    Course: "M Phil",
    Description: "Master of Philosophy",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 149,
    Course: "M PED",
    Description: "Master of Physical Education",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 35,
    Course: "MPT",
    Description: "Master of Physiotherapy",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 30,
    Course: "Master of Public Health",
    Description: "Master of Public Health",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 14,
    Course: "M Sc",
    Description: "Master of Science",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 16,
    Course: "MSW",
    Description: "Master of Social Work",
    "Institution type": "DEGREE",
  },
  {
    "Sl No.": 195,
    Course: "M Tech",
    Description: "Master of Technology",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 176,
    Course: "MTA",
    Description: "Master of Tourism Administration",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 37,
    Course: "MVSC",
    Description: "Master of Veterinary Science",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 169,
    Course: "MPH",
    Description: "Masters in public Health",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 146,
    Course: "LLM",
    Description: "Masters of LawsÂ",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 32,
    Course: "MD",
    Description: "Medical degrees",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 165,
    Course: "MIT",
    Description: "Medical Imaging Technology",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 166,
    Course: "MLT",
    Description: "Medical Lab Technology",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 36,
    Course: "MS (Medical)",
    Description: "MS (Medical)",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 175,
    Course: "MS (Professional)",
    Description: "MS (Professional)",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 198,
    Course: "MS (Technical)",
    Description: "MS (Technical)",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 172,
    Course: "MPVA",
    Description: "MULTI PURPOSE VETERINARY ASSISTANT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 177,
    Course: "NST",
    Description: "Nursery Training",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 38,
    Course: "Pharm D Post baccalaureate",
    Description: "Pharm D Post baccalaureate",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 180,
    Course: "Post Graduation Diploma Cours",
    Description: "Post Graduation Diploma Courses",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 39,
    Course: "Pharma D",
    "Institution type": "MEDICAL",
  },
  {
    "Sl No.": 40,
    Course: "PHD",
    "Institution type": "PHD",
  },
  {
    "Sl No.": 62,
    Course: "BSc Ed",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 67,
    Course: "BVOC",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 70,
    Course: "CANS",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 71,
    Course: "CARDIOLOGY TECHNICIAN",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 72,
    Course: "CAT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 73,
    Course: "CCARDIO",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 74,
    Course: "CCTC",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 75,
    Course: "CECG",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 76,
    Course: "CEPT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 77,
    Course: "CHI",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 78,
    Course: "CHT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 79,
    Course: "CLT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 80,
    Course: "CMLT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 81,
    Course: "CMXT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 82,
    Course: "COT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 83,
    Course: "COTT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 84,
    Course: "CRA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 85,
    Course: "CRI",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 86,
    Course: "CRUST",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 87,
    Course: "CTT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 90,
    Course: "DAM",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 91,
    Course: "DANS",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 92,
    Course: "DBBT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 93,
    Course: "DCARDIO",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 94,
    Course: "DCBR",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 95,
    Course: "DCRE",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 96,
    Course: "DDHY",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 97,
    Course: "DDIALY",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 98,
    Course: "DDRA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 99,
    Course: "DDTH",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 100,
    Course: "DEAIE",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 101,
    Course: "DECG",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 102,
    Course: "DECSE(MR)",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 103,
    Course: "DENTAL HYGENIST",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 104,
    Course: "DEPT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 105,
    Course: "DFEM",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 106,
    Course: "DHA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 107,
    Course: "DHFSM",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 108,
    Course: "DHI",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 109,
    Course: "DHLS",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 110,
    Course: "DHLST",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 111,
    Course: "DHMCT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 113,
    Course: "DMIT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 114,
    Course: "DMLT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 115,
    Course: "DMRD",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 116,
    Course: "DMRT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 117,
    Course: "DMST",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 118,
    Course: "DMSY",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 119,
    Course: "DMXT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 120,
    Course: "DO",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 121,
    Course: "DOA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 122,
    Course: "DOM",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 123,
    Course: "DOT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 124,
    Course: "DOTT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 125,
    Course: "DPM",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 126,
    Course: "DPMT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 127,
    Course: "DPT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 128,
    Course: "DREST",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 129,
    Course: "DRGA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 130,
    Course: "DRTT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 131,
    Course: "DRUST",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 132,
    Course: "DSE",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 133,
    Course: "DSME",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 134,
    Course: "DSWMECH",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 135,
    Course: "DTCD",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 136,
    Course: "DTE",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 137,
    Course: "DTT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 138,
    Course: "DVR",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 139,
    Course: "FWT",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 140,
    Course: "GNM (NURSING)",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 141,
    Course: "IMA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 142,
    Course: "IMSC",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 164,
    Course: "MHRD",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 170,
    Course: "MPHA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 171,
    Course: "MPHW",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 173,
    Course: "MRM",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 174,
    Course: "MRMLV",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 178,
    Course: "PBBSC(NURSING)",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 179,
    Course: "PMOA",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 181,
    Course: "SDEBM",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 182,
    Course: "SDECN",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 183,
    Course: "SDECP",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 184,
    Course: "SDEES",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 185,
    Course: "SDEIE",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 186,
    Course: "SDETV",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 187,
    Course: "UGDPET",
    "Institution type": "PROFESSIONAL",
  },
  {
    "Sl No.": 193,
    Course: "INTEGRATED ENGINEERING B TECH",
    "Institution type": "TECHNICAL",
  },
  {
    "Sl No.": 199,
    Course: "MSIT",
    "Institution type": "TECHNICAL",
  },
];
